# Generated by Django 6.0.7 on 2026-07-11 17:38

import core.models.user
import core.validators.cpf
import core.validators.email
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, help_text='Indica que este usuário está ativo.', verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica que este usuário pode acessar o Admin.', verbose_name='Usuário é da equipe')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('cpf', models.CharField(max_length=11, validators=[core.validators.cpf.validate_cpf], verbose_name='CPF')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('profile_picture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.image', verbose_name='Foto de perfil')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'core.user',
            },
            managers=[
                ('objects', core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone de contato/Telefone comercial')),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True, validators=[core.validators.email.validate_email], verbose_name='Email de contato')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Empresa aprovada no sistema')),
                ('trade_name', models.CharField(verbose_name='Nome Fantasia')),
                ('legal_name', models.CharField(verbose_name='Razão Social')),
                ('state_registration', models.CharField(verbose_name='Inscrição Estadual')),
                ('articles_of_association_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Documento de Contrato Social')),
                ('certificate_of_good_stading_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Documento de Certidões Negativas')),
                ('state_operating_license_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Documento de Licensa de Operação Estadual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Empresa (Usuário)')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'core.company',
            },
        ),
        migrations.CreateModel(
            name='CompanyRouteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da rota')),
                ('commom_address', models.CharField(help_text='CEP do endereço', max_length=9, verbose_name='Endereço em comum dentre os passageiros')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_groups', to='core.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Grupo de Rota da Empresa',
                'verbose_name_plural': 'Grupos de Rotas das Empresas',
                'db_table': 'core.company_route_group',
            },
        ),
        migrations.CreateModel(
            name='CompanyRouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_hour', models.TimeField(blank=True, null=True, verbose_name='Hora de ida')),
                ('return_hour', models.TimeField(blank=True, null=True, verbose_name='Hora de retorno')),
                ('route_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.companyroutegroup', verbose_name='Grupo de Rota')),
            ],
            options={
                'verbose_name': 'Horário da Rota',
                'verbose_name_plural': 'Horários das Rotas',
                'db_table': 'core.company_route_schedule',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado na empresa')),
                ('cnh', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnh', to='uploader.document', verbose_name='CNH')),
                ('group_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='core.companyroutegroup', verbose_name='Grupo de Rota')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista (Usuário)')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'core.driver',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado na empresa')),
                ('group_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='core.companyroutegroup', verbose_name='Grupo de Rota')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='passenger', to=settings.AUTH_USER_MODEL, verbose_name='Passageiro (Usuário)')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
                'db_table': 'core.passenger',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de término')),
                ('real_time_driver_tracking', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Localização real do motorista:')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.company', verbose_name='Empresa')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='core.driver', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'db_table': 'core.route',
                'required_db_features': ['gis_enabled'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(max_length=50, verbose_name='Descrição do item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_items', to='core.route', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Item Perdido',
                'verbose_name_plural': 'Itens Perdidos',
                'db_table': 'core.lost_item',
            },
        ),
        migrations.CreateModel(
            name='ConfirmPassengerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(blank=True, null=True, verbose_name='Confirmado')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_confirms', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_confirms', to='core.route', verbose_name='Rota')),
            ],
            options={
                'verbose_name': 'Confirmação de Usuário na Rota',
                'verbose_name_plural': 'Confirmações de Usuários na Rotas',
                'db_table': 'core.confirm_passenger_route',
            },
        ),
        migrations.AddConstraint(
            model_name='companyroutegroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_route_name'),
        ),
        migrations.AddConstraint(
            model_name='companyrouteschedule',
            constraint=models.CheckConstraint(condition=models.Q(('return_hour__gt', models.F('go_hour'))), name='return_hour_after_go_hour'),
        ),
        migrations.AddConstraint(
            model_name='companyrouteschedule',
            constraint=models.UniqueConstraint(fields=('return_hour', 'go_hour'), name='unique_return_and_go_hour'),
        ),
    ]
