# Generated by Django 5.2.13 on 2026-05-02 02:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageiro',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passageiro',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.image', verbose_name='Foto de perfil'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=255, verbose_name='Telefone de contato/Telefone comercial')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='Email de contato')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('articles_of_association_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document')),
                ('certificate_of_good_stading_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document')),
                ('state_operating_license_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanyRouteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commom_adress', models.CharField(blank=True, help_text='CEP do endereço', max_length=9, null=True, verbose_name='Endereço em comum dentre os passageiros')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'verbose_name': 'Grupo de Rota da Empresa',
                'verbose_name_plural': 'Grupos de Rotas das Empresas',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_route', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.companyroutegroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_route', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.companyroutegroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
            },
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Motorista',
        ),
        migrations.DeleteModel(
            name='Passageiro',
        ),
    ]
