# Generated by Django 6.0.4 on 2026-04-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='motoristas', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passageiros', to='core.company', verbose_name='Empresa'),
        ),
    ]
