# Generated by Django 6.0.7 on 2026-07-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='real_time_driver_tracking',
        ),
    ]
