# Generated by Django 6.0.7 on 2026-07-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_route_real_time_driver_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyroutegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Grupo'),
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField(verbose_name='Pontos de Parada')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Rota')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='core.companyroutegroup', verbose_name='Grupo de Rotas')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'db_table': 'routes.path',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de término')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travels', to='core.company', verbose_name='Empresa')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travels', to='core.driver', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'db_table': 'router.travel',
            },
        ),
        migrations.AlterField(
            model_name='confirmpassengerroute',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_confirms', to='core.travel', verbose_name='Rota'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_items', to='core.travel', verbose_name='Rota'),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
