# Generated by Django 5.2.13 on 2026-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_passageiro_empresa_remove_motorista_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Empresa aprovada no sistema'),
        ),
    ]
