# Generated by Django 5.1.7 on 2026-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_driver_empresa_passenger_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certidoes_negativas',
            field=models.FileField(blank=True, help_text='PDF, JPG, JPEG ou PNG (máx. 10MB)', null=True, upload_to='company_documents/certidoes_negativas/%Y/%m/', verbose_name='Certidões Negativas'),
        ),
        migrations.AddField(
            model_name='company',
            name='contrato_social',
            field=models.FileField(blank=True, help_text='PDF, JPG, JPEG ou PNG (máx. 10MB)', null=True, upload_to='company_documents/contrato_social/%Y/%m/', verbose_name='Contrato Social'),
        ),
        migrations.AddField(
            model_name='company',
            name='licenca_operacao',
            field=models.FileField(blank=True, help_text='PDF, JPG, JPEG ou PNG (máx. 10MB)', null=True, upload_to='company_documents/licenca_operacao/%Y/%m/', verbose_name='Licença de Operação'),
        ),
    ]
