# Generated by Django 5.2.13 on 2026-05-02 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyroutegroup',
            name='commom_adress',
        ),
        migrations.AddField(
            model_name='companyroutegroup',
            name='commom_address',
            field=models.CharField(help_text='CEP do endereço', max_length=9, verbose_name='Endereço em comum dentre os passageiros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email de contato'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone de contato/Telefone comercial'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Empresa (Usuário)'),
        ),
        migrations.AlterField(
            model_name='companyroutegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome da rota'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação do usuário'),
        ),
    ]
