# Generated by Django 6.0.7 on 2026-07-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_companyroutegroup_name_path_travel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.companyroutegroup', verbose_name='Grupo de Rotas')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'routes.vehicles',
            },
        ),
    ]
