# Generated by Django 6.0.4 on 2026-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_passenger_empresa_remove_driver_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
