# Generated by Django 6.0.7 on 2026-07-29 22:17

import core.validators.cnpj
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[core.validators.cnpj.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Usuário está ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Usuário é da equipe'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='accounts_company',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='accounts_driver',
        ),
        migrations.AlterModelTable(
            name='passenger',
            table='accounts_passenger',
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
