# Generated by Django 5.2.13 on 2026-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_companyroutegroup_commom_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
