# Generated by Django 5.2.13 on 2026-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_driver_is_approved_passenger_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Motorista aprovado na empresa'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Passageiro aprovado na empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
    ]
