# Generated by Django 6.0.7 on 2026-07-31 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_cnpj_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle',
            table='routes_vehicles',
        ),
    ]
