# Generated by Django 5.2.12 on 2026-04-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_accessibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cnpj', models.CharField(max_length=14)),
                ('business_address', models.TextField()),
                ('identification_document_url', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accessibility', to='core.profile'),
        ),
    ]
