# Generated by Django 5.2.12 on 2026-04-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_alter_accessibility_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('trade_name', models.CharField(max_length=50)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
    ]
