# Generated by Django 5.2.13 on 2026-05-03 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_company_cnpj'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='articles_of_association_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Documento de Contrato Social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='certificate_of_good_stading_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Documento de Certidões Negativas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state_operating_license_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Documento de Licensa de Operação Estadual'),
        ),
    ]
