# Generated by Django 5.2.12 on 2026-04-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_company_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
