# Generated by Django 5.2.13 on 2026-05-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_company_articles_of_association_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyroutegroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='group_route',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.companyroutegroup', verbose_name='Grupo de Rota'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado na empresa'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='group_route',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.companyroutegroup', verbose_name='Grupo de Rota'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado na empresa'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
