# Generated by Django 5.2.13 on 2026-05-06 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_companyroutegroup_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=django.utils.timezone.now, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
