# Generated by Django 5.2.12 on 2026-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Admin_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_passenger_contracts', models.BooleanField(default=False)),
                ('approve_drivers_contracts', models.BooleanField(default=False)),
                ('access_route_log', models.BooleanField(default=False)),
                ('access_company_settings', models.BooleanField(default=False)),
                ('generate_registration_links', models.BooleanField(default=False)),
                ('create_new_admins', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permissões de Administrador da Empresa',
                'verbose_name_plural': 'Permissões de Administradores das Empresas',
            },
        ),
        migrations.AlterModelOptions(
            name='accessibility',
            options={'verbose_name': 'Acessibilidade', 'verbose_name_plural': 'Acessibilidades'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='company_profile',
            options={'verbose_name': 'Perfil de Empresa', 'verbose_name_plural': 'Perfis de Empresa'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='identification_document_url',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='trade_name',
        ),
        migrations.AddField(
            model_name='company',
            name='negative_certificates_document_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='social_contract_document_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='state_operating_license_document_url',
            field=models.CharField(default=99, max_length=255),
            preserve_default=False,
        ),
    ]
