# Generated by Django 5.2.12 on 2026-04-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_company_admin_permission_alter_accessibility_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_email', models.EmailField(max_length=255, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'verbose_name': 'Administrador de Empresa',
                'verbose_name_plural': 'Administradores de Empresa',
            },
        ),
    ]
