# Generated by Django 5.2.12 on 2026-04-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_company_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('register_email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Administrador do Sistema',
                'verbose_name_plural': 'Administradores do Sistema',
            },
        ),
    ]
