# Generated by Django 5.2.13 on 2026-05-29 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_created_at_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='group_route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.companyroutegroup', verbose_name='Grupo de Rota'),
        ),
    ]
