# Generated by Django 5.2.13 on 2026-06-05 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_driver_group_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(default=django.utils.timezone.now, verbose_name='Razão Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='trade_name',
            field=models.CharField(default=django.utils.timezone.now, verbose_name='Nome Fantasia'),
            preserve_default=False,
        ),
    ]
