# Generated by Django 5.2.12 on 2026-04-10 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_system_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Registration_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_responsible_request', models.CharField(max_length=200)),
                ('final_status', models.CharField(max_length=20)),
                ('reason_rejection', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registration_request', to='core.company')),
                ('system_admin_finished_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.system_admin')),
            ],
            options={
                'verbose_name': 'Solicitação de Cadastro de Empresa',
                'verbose_name_plural': 'Solicitações de Cadastro de Empresas',
            },
        ),
    ]
