# Generated by Django 5.2.12 on 2026-04-10 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_company_registration_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=20)),
                ('home_address', models.TextField()),
                ('reason_rejection', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('final_status', models.CharField(max_length=20)),
                ('person_cpf', models.CharField(max_length=14)),
                ('company_admin_finished_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company_admin')),
            ],
            options={
                'verbose_name': 'Solicitação de Contrato',
                'verbose_name_plural': 'Solicitações de Contratos',
            },
        ),
    ]
