# Generated by Django 5.2.13 on 2026-06-05 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_company_legal_name_company_trade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state_registration',
            field=models.CharField(default=django.utils.timezone.now, verbose_name='Inscrição Estadual'),
            preserve_default=False,
        ),
    ]
