# Generated by Django 5.2.12 on 2026-04-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contract_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128)),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company_registration_request')),
                ('contract_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contract_request')),
            ],
            options={
                'verbose_name': 'Link de Registro',
                'verbose_name_plural': 'Links de Registro',
            },
        ),
    ]
