# Generated by Django 5.2.13 on 2026-06-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_birthday'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cnh',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='CNH'),
        ),
    ]
