# Generated by Django 5.2.12 on 2026-04-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_register_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.TextField()),
                ('register_phone', models.CharField(max_length=45)),
                ('register_email', models.EmailField(max_length=254)),
                ('driver_cpf', models.CharField(max_length=14)),
                ('password_hash', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='core.profile')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
    ]
