# Generated by Django 5.2.13 on 2026-06-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_driver_cnh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='group_route',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.companyroutegroup', verbose_name='Grupo de Rota'),
        ),
    ]
