# Generated by Django 5.2.12 on 2026-04-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('common_address_passengers', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Grupo de Rota',
                'verbose_name_plural': 'Grupos de Rota',
            },
        ),
    ]
