# Generated by Django 5.2.12 on 2026-04-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_route_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_request',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.route_group'),
        ),
        migrations.AddField(
            model_name='driver',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.route_group'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.route_group'),
        ),
    ]
