# Generated by Django 5.2.12 on 2026-04-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contract_request_group_driver_group_passenger_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('real_time_driver_tracking', models.TextField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trip_report', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
    ]
