# Generated by Django 5.2.12 on 2026-04-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmed_Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_address', models.TextField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.passenger')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.route')),
            ],
            options={
                'verbose_name': 'Passageiro_Confirmado',
                'verbose_name_plural': 'Passageiros Confirmados',
            },
        ),
    ]
