# Generated by Django 5.2.12 on 2026-04-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_confirmed_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.passenger')),
                ('route_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.route')),
            ],
            options={
                'verbose_name': 'Item Perdido',
                'verbose_name_plural': 'Itens Perdidos',
            },
        ),
    ]
