# Generated by Django 5.2.12 on 2026-04-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_lost_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Job_Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('region', models.TextField()),
                ('requirements', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'verbose_name': 'Vaga_de_Motorista',
                'verbose_name_plural': 'Vagas de Motorista',
            },
        ),
    ]
