# Generated by Django 5.2.12 on 2026-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_driver_job_opening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Recovery_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register_email', models.EmailField(max_length=254)),
                ('pending', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Código de Recuperação de Conta',
                'verbose_name_plural': 'Códigos de Recuperação de Conta',
            },
        ),
    ]
