# Generated by Django 5.2.12 on 2026-04-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_account_recovery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company'),
        ),
    ]
