# Generated by Django 5.2.12 on 2026-04-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_company_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_admin_permission',
            name='admin',
            field=models.OneToOneField(default=99, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='core.company_admin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessibility',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessibility', to='core.profile'),
        ),
    ]
