# Generated by Django 5.2.12 on 2026-04-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_company_admin_permission_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmed_passenger',
            options={'verbose_name': 'Confirmar Pasajero', 'verbose_name_plural': 'Confirmar Pasajeros'},
        ),
    ]
