# Generated by Django 6.1 on 2026-08-27 18:13

import uploader.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=uploader.models.document.get_document_storage, upload_to=uploader.models.document.document_file_path),
        ),
    ]
