from authenticator.views.auth import CustomLogoutView, CustomTokenObtainPairView, CustomTokenRefreshView
from authenticator.views.company import CompanyViewSet
from authenticator.views.company_route_group import CompanyGroupRouteViewSet
from authenticator.views.driver import DriverViewSet
from authenticator.views.passenger import PassengerViewSet
from authenticator.views.email_token import EmailTokenViewSet