# Generated by Django 6.0.7 on 2026-08-02 02:39

import authenticator.models.user
import authenticator.validators.cnpj
import authenticator.validators.cpf
import authenticator.validators.email
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Usuário é da equipe')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('cpf', models.CharField(max_length=11, validators=[authenticator.validators.cpf.validate_cpf], verbose_name='CPF')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('profile_picture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.image', verbose_name='Foto de perfil')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'authenticator_user',
            },
            managers=[
                ('objects', authenticator.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[authenticator.validators.cnpj.validate_cnpj], verbose_name='CNPJ')),
                ('state_registration', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone de contato')),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True, validators=[authenticator.validators.email.validate_email], verbose_name='Email de contato')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Aprovada no sistema')),
                ('articles_of_association_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Contrato Social')),
                ('certificate_of_good_stading_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Certidões Negativas')),
                ('state_operating_license_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.document', verbose_name='Licença de Operação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Empresa (Usuário)')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'accounts_company',
                'ordering': ['trade_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRouteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('common_cep', models.CharField(help_text='CEP do endereço comum aos passageiros', max_length=9, verbose_name='CEP em comum')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_groups', to='authenticator.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Grupo de Rota',
                'verbose_name_plural': 'Grupos de Rotas',
                'db_table': 'authenticator_company_route_group',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Aprovado na empresa')),
                ('cnh', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cnh', to='uploader.document', verbose_name='CNH')),
                ('group_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='authenticator.companyroutegroup', verbose_name='Grupo de Rota')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='Motorista (Usuário)')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'accounts_driver',
                'ordering': ['user__name'],
            },
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('consumed', models.BooleanField(db_index=True, default=False, verbose_name='Consumido')),
                ('token_type', models.CharField(choices=[('new-password', 'Nova Senha'), ('new-user', 'Novo Usuário'), ('new-email', 'Novo Email')], default='new-user', max_length=20, verbose_name='Tipo de Token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Email Token',
                'verbose_name_plural': 'Email Tokens',
                'db_table': 'authenticator_email_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado na empresa')),
                ('group_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='authenticator.companyroutegroup', verbose_name='Grupo de Rota')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='passenger', to=settings.AUTH_USER_MODEL, verbose_name='Passageiro (Usuário)')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
                'db_table': 'accounts_passenger',
                'ordering': ['user__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='companyroutegroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_route_name'),
        ),
    ]
