# Generated by Django 6.1 on 2026-08-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='company',
            name='complement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='company',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da geocodificação do endereço'),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='companyroutegroup',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da geocodificação'),
        ),
        migrations.AddField(
            model_name='companyroutegroup',
            name='reference_latitude',
            field=models.FloatField(blank=True, help_text='Ponto central da área de captação do grupo, usado para calcular rotas e paradas.', null=True, verbose_name='Latitude de referência'),
        ),
        migrations.AddField(
            model_name='companyroutegroup',
            name='reference_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude de referência'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da geocodificação do endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, help_text='Número da casa/apartamento. Use "S/N" quando não houver numeração.', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
    ]
