# Generated by Django 6.1 on 2026-08-27 01:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_company_cep_company_city_company_complement_and_more'),
        ('router', '0004_vehicle_color_vehicle_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da avaliação')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='authenticator.driver', verbose_name='Motorista')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Passageiro')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_ratings', to='router.travel', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Avaliação de motorista',
                'verbose_name_plural': 'Avaliações de motoristas',
                'db_table': 'authenticator_driver_rating',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('driver', 'passenger', 'travel'), name='unique_rating_per_travel')],
            },
        ),
    ]
