from core.serializers.user import UserSerializer, UserRegistrationSerializer
from core.serializers.passenger import PassengerSerializer
from core.serializers.driver import DriverSerializer
from core.serializers.company import CompanyRegistrationSerializer, CompanySerializer
from core.serializers.company_route_group import CompanyRouteGroupSerializer