from .user import UserSerializer, UserRegistrationSerializer
from .passenger import PassageiroSerializer, RegistroPassageiroSerializer
from .driver import MotoristaSerializer, RegistroMotoristaSerializer
from .company import EmpresaSerializer, RegistroEmpresaSerializer