from authenticator.serializers.company import CompanyCreateSerializer,CompanyListAndRetrieveSerializer, CompanyPatchSerializer
from authenticator.serializers.company_route_group import CompanyRouteGroupSerializer
from authenticator.serializers.driver import DriverCreateSerializer, DriverListAndRetrieveSerializer, DriverPatchSerializer
from authenticator.serializers.passenger import PassengerCreateSerializer, PassengerListAndRetrieveSerializer, PassengerPatchSerializer
from authenticator.serializers.user import BaseProfileCreateSerializer,BaseProfilePatchSerializer,UserCreateSerializer, UserCreateSerializer,UserListAndRetriveSerializer,UserPatchSerializer
from authenticator.serializers.email_token import EmailTokenCreateSerializer, EmailTokenVerifySerializer