from router.serializers.company_route_schedule import CompanyRouteScheduleCreateSerializer, CompanyRouteScheduleListAndRetrieveSerializer, CompanyRouteSchedulePatchSerializer
from router.serializers.confirm_passenger_route import (
    ConfirmPassengerRouteListAndRetrieveSerializer as ConfirmPassengerRouteListAndRetrieveSerializer,
)
from router.serializers.lost_item import LostItemCreateSerializer,LostItemListAndRetrieveSerializer,LostItemPatchSerializer
from router.serializers.path import PathCreateSerializer,PathListAndRetrieveSerializer,PathPatchSerializer
from router.serializers.vehicle import VehicleCreateSerializer,VehicleListAndRetrieveSerializer,VehiclePatchSerializer
