# Generated by Django 6.0.7 on 2026-08-02 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField(verbose_name='Pontos de Parada')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Rota')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='authenticator.companyroutegroup', verbose_name='Grupo de Rotas')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'db_table': 'router_path',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de término')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travels', to='authenticator.company', verbose_name='Empresa')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travels', to='authenticator.driver', verbose_name='Motorista')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.path', verbose_name='Rota (Path)')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'db_table': 'router_travel',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255, verbose_name='Descrição do item')),
                ('status', models.CharField(choices=[('reported', 'Relatado'), ('found', 'Encontrado'), ('returned', 'Devolvido')], default='reported', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_items', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_items', to='router.travel', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Item Perdido',
                'verbose_name_plural': 'Itens Perdidos',
                'db_table': 'router_lost_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP da garagem')),
                ('plate', models.CharField(help_text='Placa do veículo', max_length=10, unique=True, verbose_name='Placa')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='authenticator.companyroutegroup', verbose_name='Grupo de Rotas')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'router_vehicles',
                'ordering': ['group__name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_hour', models.TimeField(verbose_name='Hora de ida')),
                ('return_hour', models.TimeField(verbose_name='Hora de retorno')),
                ('route_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='authenticator.companyroutegroup', verbose_name='Grupo de Rota')),
            ],
            options={
                'verbose_name': 'Horário da Rota',
                'verbose_name_plural': 'Horários das Rotas',
                'db_table': 'router_company_route_schedule',
                'constraints': [models.CheckConstraint(condition=models.Q(('return_hour__gt', models.F('go_hour'))), name='return_hour_after_go_hour'), models.UniqueConstraint(fields=('route_group', 'go_hour', 'return_hour'), name='unique_schedule_per_group')],
            },
        ),
        migrations.CreateModel(
            name='ConfirmPassengerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da confirmação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_confirms', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_confirms', to='router.travel', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Confirmação de passageiro',
                'verbose_name_plural': 'Confirmações de passageiros',
                'db_table': 'router_confirm_passenger_route',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('travel', 'user'), name='unique_user_travel_confirmation')],
            },
        ),
    ]
