# Generated by Django 6.1 on 2026-08-27 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_vehicle_capacity_vehicle_driver_vehicle_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude atual'),
        ),
        migrations.AddField(
            model_name='travel',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude atual'),
        ),
        migrations.AddField(
            model_name='travel',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização de localização'),
        ),
        migrations.AddField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('in_progress', 'Em andamento'), ('finished', 'Finalizada'), ('canceled', 'Cancelada')], db_index=True, default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='router.path', verbose_name='Rota (Path)'),
        ),
    ]
