# Generated by Django 6.1 on 2026-08-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_travel_current_latitude_travel_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Lista de comodidades, ex.: ["Ar-condicionado", "Wi-Fi", "Cinto de segurança"]', verbose_name='Características'),
        ),
    ]
